ManasUPSC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from upscapp.views import *
from User.views import *
app_name = "upscapp"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('home/',homeview),
    # path('success/',successview),
    #path('', views.homeview),
    path('services/', servicesview),
    path('contact/', contactview),
    path('gallary/', gallaryview),
    path('feedback/', feedbackview),
    path('post/', post_list),
    path('post_create/', postcreation_view),
    path('post/<int:pk>/', post_detail, name='post_detail'),
    path('user/', include('User.urls', namespace="user")),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

User/urls.py
from django.conf.urls import url
from User import views
app_name = 'user'


urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^user_logout/$', views.user_logout, name='user_logout'),
    url(r'^change_password/$', views.ChangePasswordView, name="change_password"),
    url(r'^profile/$', views.uprofile, name='profile'),
    url(r'^logout/$', views.logout_view, name='logout'),

]

upscapp/models.py
from django.db import models
from User.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.utils import timezone


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    parent = models.ForeignKey(
        'self', null=True, blank=True, on_delete=models.CASCADE)
    content_type = models.ForeignKey(
        ContentType, related_name="comments", on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    text = models.TextField(null=False, blank=False)

    def __str__(self):
        return self.text[:20]

    def children(self):
        return Comment.objects.filter(object_id=self.id)

    # @property
    # def get_content_type(self):
    #     post = self
    #     content_type = ContentType.objects.get_for_model(post.__class__)
    #     return content_type


class ServicesData(models.Model):
    comments = GenericRelation(Comment)
    subject_code = models.IntegerField(primary_key=True)
    subject_name = models.CharField(max_length=100, unique=True)
    subject_duration = models.CharField(max_length=100)
    subject_startdate = models.DateField(max_length=100)
    subject_starttime = models.TimeField(max_length=100)
    subject_instructor_name = models.CharField(max_length=100)
    subject_instructor_experience = models.CharField(max_length=100)

    def __str__(self):
        return self.subject_name


class FeedBackData(models.Model):
    comments = GenericRelation(Comment)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    adress = models.CharField(max_length=250)
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=100)
    feedback = models.CharField(max_length=250)

    def __str__(self):
        return self.first_name


class ContactData(models.Model):

    name = models.CharField(max_length=25)
    GENDER_CHOICE = (
        ('Male', 'Male'),
        ('Female', 'Female')
    )
    gender = models.CharField(max_length=10, choices=GENDER_CHOICE)
    email = models.EmailField(max_length=30)
    mobile = models.BigIntegerField()
    about = models.CharField(max_length=500)


class Post(models.Model):
    post = GenericRelation(Comment)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    image = models.ImageField(upload_to='blogpic',
                              null=True,
                              blank=True,)
    content = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateField(blank=True, null=True)
    updated = models.DateTimeField(auto_now_add=False)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def publish(self):
        self.published_date = timezone.now()
        self.save()

templates/base.html
{% load staticfiles %}
<html>
<head>
    <title>Micro UPSC</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/infinite.min.js' %}"></script>
</head>
<body>
<!--nav start-->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/home">MicroUPSC</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/home">Home</a></li>
      <li class="item"><a href="/services">Batches</a></li>
      <li class="item"><a href="/contact">Contact</a></li>
      <li class="item"><a href="/gallary">Gallary</a></li>
      <li class="item"><a href="/feedback">Feedback</a></li>
      <li class="item"><a href="/post">Blog</a></li>
      <li class="item"><div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">User
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <li><a href="/user/change_password/">Change Password</a></li>
    <li><a href="/user/profile/">Update User</a></li>
    <li><a href="/user/logout/">Logout</a></li>
  </ul>
</div></li>
    </ul>
  </div>
</nav>
<!--nav end-->
<h1 style="text-align: center; color: rebeccapurple;">Welcome To Micro UPSC</h1>
{% block content %}
{% endblock %}
<!--<footer>
    <h5 id="foot">&copy; CopyRights By MicroUPSC</h5>
</footer>-->
</body>
</html>

templates/change_password.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {{ pform.as_p }}
  <button type="submit">Save changes</button>
</form>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
<html>
<head>
    <title>Contact Page</title>
</head>
<body>
{% block content %}
<style>
    .header {
        color: #36A0FF;
        font-size: 27px;
        padding: 10px;
    }

    .bigicon {
        font-size: 35px;
        color: #36A0FF;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
                <form class="form-horizontal" method="post">
                    <fieldset>
                        <legend class="text-center header">Contact us</legend>
                        <form>
                        {% csrf_token %}
                        {{cform.as_p}}<br>
                        <input type="submit",value="send",class="btn btn-primary">
                      </form>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
</body>
</html>

templates/feedback.html
{% extends 'base.html' %}
<html>
<head>
    <title>Feedback Page</title>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<style>
    form {
            background-color: peru;
            padding: 20px;
            box-shadow: 2px 2px 10px black;)}
</style>
<body>
{% block content %}
        <div class="container">
            <div class="row">
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="title1"> Yours Question </div>
                    <form method="post">
                        {% csrf_token %}
                        {{ fform.as_p }}<br>
                        <input type="submit" value="Submit" class="btn btn-primary">
                    </form><br>
                </div>
            </div>
        </div>
{% endblock %}
</body>
</html>

templates/gallary.html
{% extends 'base.html' %}
{% load static %}
<html>
<head>
    <title>Gallary</title>
       <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
{% block content %}
    <h2 class="text-center text-danger">Our Toppers</h2>
<div class="container">
    <div class="row">
      <div class="col-md-6">
         <div class="thumbnail">
             <img src="{% static 'images/ashwin.png' %}" alt="Lights"
               style="width:100%; height: 55%">
         </div>
      </div>
      <div class="col-md-6">
          <div class="thumbnail">
              <img src="{% static 'images/upscVinisha.jpeg' %}" alt="Nature"
                   style="width:100%; height: 55%">
          </div>
      </div>
    </div>


    <div class="row">
      <div class="col-md-6">
         <div class="thumbnail">
            <img src="{% static 'images/upsc3.jpg' %}" alt="Lights"
                 style="width:100%; height: 50%">
         </div>
      </div>
      <div class="col-md-6">
          <div class="thumbnail">
             <img src="{% static 'images/mana.jpg' %}" alt="Nature"
                  style="width:100%; height: 50%">
          </div>
      </div>
    </div>


    <div class="row">
       <div class="col-md-6">
          <div class="thumbnail">
             <img src="{% static 'images/upsc10.jpg' %}" alt="Lights"
                  style="width:100%; height: 50%">
          </div>
       </div>
       <div class="col-md-6">
          <div class="thumbnail">
             <img src="{% static 'images/Upsc8.jpg' %}" alt="Nature"
                  style="width:100%; height: 50%">
          </div>
       </div>
    </div>
    
    <div class="row">
       <div class="col-md-6">
           <div class="thumbnail">
               <img src="{% static 'images/laxman.jpeg' %}" alt="Lights"
                    style="width:100%; height: 60%">
           </div>
       </div>
       <div class="col-md-6">
           <div class="thumbnail">
               <img src="{% static 'images/we.jpg' %}" alt="Nature" style="width:100%; height: 60%">
           </div>
       </div>
    </div>
</div>
{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
<html>
<head>
    <title>Home Page</title>
</head>
<style>
    body{
        background-image: {% static 'images/upsc3.jpg' %};

    *{
        margin: 0;
        padding: 0;
        font-family: "Century Gothic";
    }
    header{
        background-image:linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url("https://i.ytimg.com/vi/pc5FpSzm4_E/maxresdefault.jpg");
        height: 100vh;
        background-size: cover;
        background-position: center;
    }
    ul{
        list-style-type: none;
        float: right;
        margin-top: 25px;
    }
    ul li{
        display: inline-block;
    }
    ul li a{
        text-decoration: none;
        color: #fff;
        padding: 5px 20px;
        border: 1px solid transparent;
        transition: 0.6s ease;
    }
    ul li a:hover{
        background-color: #fff;
        color: #000 ;
    }
    ul li.active a{
        background-color: #fff;
        color: #000;
    }
    .title{
        position: absolute;
        top: 50%;
        left: 30%;
        color: #fff;
        font-size: 25px;

    }
    .button{
        position: absolute;
        top: 65%;
        left: 38%;
    }
    .btn{
        border: 1px solid #fff;
        padding: 10px 30px;
        color: #fff;
        text-decoration: none;
    }
    .btn:hover{
        background-color: #fff;
        color: #000;
    }
    .txt{
        position: absolute;
        top: 72%;
        left: 25%;
        font-size: 12px;
        color: #fff;
    }





</style>
<body>
{% block content %}
 <div class="title">
        <h1>Micro UPSC</h1>
    </div>
    <div class="button">
        <a href="https://www.youtube.com/channel/UCrC8mOqJQpoB7NuIMKIS6rQ" class="btn">Watch Videos</a>
        <a href="/gallary/" class="btn">Watch Images</a>
    </div>

    <div class="txt">
        <pre>
            Micro UPSC started 100years ago, We are the no.1 Learning Platform in India.
        </pre>
    </div>
    <div class="container">
    </div>
{% endblock %}
</body>
</html>

templates/index.html
{% extends "login_base.html" %}
{%block menu%}{%endblock%}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Indias best learning platform !!!</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/login.html
{% extends 'login_base.html' %}
{% block content %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'user:user_login' %}">
          {% csrf_token %}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
</div>
{% endblock %}

templates/login_base.html
{% load staticfiles %}
<html>
<head>
    <title>Micro UPSC</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<style> 
  .container{
    color:purple;
     }
</style>

<body>
  <nav class="navbar navbar-default">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">MicroUPSC</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'user:register' %}">Register</a></li> 
          <li><a class="navbar-link" href="{% url 'user:user_login' %}">Login</a></li>    
          </ul>
      </div>
<h1 style="text-align: center; color: rebeccapurple;">Welcome To Micro UPSC</h1>
{% block content %}
{% endblock %}
<footer>
    <h5 id="foot">&copy; CopyRights By MicroUPSC</h5>
</footer>
</body>
</html>

templates/post_detail.html
{% extends 'base.html' %}

{% block content %}
<style>
	body{
		background-color: lightblue;
	}
</style>
    <div class="row">
    <div class="col-lg-6">

    {% if post %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.content|linebreaksbr }}</p>

    <form method="post" action=".">
        {% csrf_token %}
        <label for="id_text"></label>
        <textarea name="text" cols="40" rows="10" required="" id="id_text"></textarea>
        <input type="hidden" name="object_id" value='{{post.id}}'>
        <input type="submit" value="Comment" class="btn btn-primary"><br>
     </form>


 <div class="infinite-container">
    <small><p class='lead'>Comments</p></small>
        {%for comment in comments %}
         <br>
          <div class="infinite-item">{{comment.text}}</div>
          by {{comment.user}}<br>
          <a href='#' class="rep_cmt" data-parentid="{{comment.id}}">Reply</a><br>
          {% for comment in comment.children.all %}
            {{comment}}
          {% endfor %}
        {%endfor%}
    </div>

    <div class="col-lg-6">
        <form method="POST" >
            {%csrf_token%}
        <textarea name="text" cols="20" rows="5" required="" id="id_text"></textarea>
        <input type="text" id = "parent_id" name="parent_id" hidden>
        <input type="submit" value="Comment" class="btn btn-primary"><br>
        </form>
    </div>
<div>
     {% if comments.has_next %}
    <button><a class="infinite-more-link" href="?page={{ comments.next_page_number }}">More</a></button>
     {% endif %}

    <div class="loading" style="display: none;">
      Loading...
    </div>
<script>
    
    $(document).ready(function(){
    $(".rep_cmt").click(function(){
    var parent = $(this).data('parentid')
    $("#parent_id").val(parent)
  });
});

    var infinite = new Waypoint.Infinite({
      element: $('.infinite-container')[0],
      onBeforePageLoad: function () {
        $('.loading').show();
      },
      onAfterPageLoad: function ($items) {
        $('.loading').hide();
      }
    });

</script>
{% endblock %}

templates/post_list.html
{% extends 'base.html' %}
{% block content %}
<style>
body{
	background-color: lightblue;
}
</style>
<div class='row'>
  <div class="col-lg-6">



<div>
    <h1><a href="">Blogs</a></h1>
</div>


<div class="topnav">
<form>
<input type="text" name="search_key" value="{{pie}}" placeholder="Search..">`
<input type="submit" class="btn btn-primary btn-sm" value="Submit">
</form>
</div>

{% for data in post %}
    <div>
        <p>published: {{ data.published_date }}</p>
        <h2><a href="/post/{{data.pk}}">{{ data.title }}</a></h2>
        <p>{{ data.content|linebreaksbr }}</p>
    </div>
{% endfor %}

{% if post.has_other_pages %}
  <ul class="pagination">
    {% if post.has_previous %}
      <li><a href="?page={{ post.previous_page_number }}&search_key={{key}}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in post.paginator.page_range %}
      {% if services.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}&search_key={{key}}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if post.has_next %}
      <li><a href="?page={{ post.next_page_number }}&search_key={{key}}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>

      </div>
      <div class='col-lg-6'>
       <button> <a href="/post_create">POST</a></button>
      </div>
 {% endif %}
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form action="." method="post">
    {% csrf_token %}
    {{ uform.as_p }}
    <button type="submit">Update Profile</button>
</form>
{% endblock %}

templates/registration.html
{% extends "login_base.html" %}
{% load staticfiles %}
{% block content %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/services.html
{% extends 'base.html' %}

{% block content %}

<style>
th,td{
  padding: 10px 20px;
  text-align: center;
}
</style>

<div class="topnav">
<form>
<input type="text" name="search_key" value="{{sub}}" placeholder="Search..">`
<select> 
  <option value="" >Select your option</option>
  {% for op in subject_instructor_name %}
    <option value="{{op}}" >{{op}}</option>
  {% endfor %}
</select>
<input type="submit" class="btn btn-primary btn-sm" value="Submit">
</form>
</div>

{% if services %}
        <center>
        <table id="" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th class="th-sm">Subject Code</th>
            <th class="th-sm">Subject Name</th>
            <th class="th-sm">Subject Duration</th>
            <th class="th-sm">Subject Start Date</th>
            <th class="th-sm">Subject Start Time</th>
            <th class="th-sm">Subject Instructor Name</th>
            <th class="th-sm">Subject Instructor Experience</th>
        </tr>
        </thead>
        {% for name in services %}
        <tbody>
        <tr>
            <td>{{ name.subject_code }}</td>
            <td>{{ name.subject_name }}</td>
            <td>{{ name.subject_duration }}</td>
            <td>{{ name.subject_startdate }}</td>
            <td>{{ name.subject_starttime}}</td>
            <td>{{ name.subject_instructor_name}}</td>
            <td>{{ name.subject_instructor_experience}}</td>
        </tr>
        </tbody>
         {% endfor %}
        </table>

{% if services.has_other_pages %}
  <ul class="pagination">
    {% if services.has_previous %}
      <li><a href="?page={{ services.previous_page_number }}&search_key={{key}}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in services.paginator.page_range %}
      {% if services.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}&search_key={{key}}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if services.has_next %}
      <li><a href="?page={{ services.next_page_number }}&search_key={{key}}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}

  </ul>
{% endif %}
    </center>
        
        <div class="ser">
        <h1>Services</h1>
        <pre>
         1. High Priority for study Materials.
         2. We provide 24/7 services for registered aspirants.
         3. All students will get 100% satisfaction.
         4. We provide institutions for all over in India.
         </pre>
        <a href="/home/">Back</a>
    </div>
    <div class="ach">
        <h1>Achievements</h1>
        <pre>
         1. Selected for World's best Upsc Preparation website.
         2. Thounsands of Customers for Everyday.
         3. India's all VVIPS are our Customers.
         4. Obama waited for two months for our services
        </pre>
    </div>
    {% else %}
    <h1>No Batches Available For This Time</h1>
    {% endif %}
{% endblock %}